Update github.md
wengroup/group_manual pull request #9
Opened 2023-02-16 03:40 UTC by Olanrewajuemmanuelabiodun

2023-02-20 03:51 UTC, mjwen commented
Hi @Olanrewajuemmanuelabiodun 

To clarify, what we want for this tutorial is something very similar to https://wengroup.github.io/group_manual/contributing/edit.html. The part we want to replace is `2. Making edits`. There, all edits are made via the GitHub web editor. But for this tutorial, what we want is cloning the repo to a local machine (i.e. a laptop), edit it on on the laptop, commit, push, and finally make a pull request (PR). Let me know if this is not clear.

2023-02-28 16:22 UTC, mjwen commented
@Olanrewajuemmanuelabiodun seems my comments are not addressed. For example
- you need to add instruction for for generating SSH key and upload to github
- clone from SSH not https

2023-02-28 16:25 UTC, Olanrewajuemmanuelabiodun commented
I am sorry for that. I am doing it right now.

2023-03-03 05:00 UTC, mjwen commented
@Olanrewajuemmanuelabiodun I added a few final comments. Let me know once done (can directly reply here).

2023-03-03 05:00 UTC, mjwen requested changes

2023-03-03 05:00 UTC, mjwen commented on docs/devtool/github.md
> +$ git init
This is not supposed to be here. We already cloned a git repo (which is already initialized), so we should not init it anymore.

2023-03-03 05:00 UTC, mjwen commented on docs/devtool/github.md
> +$ git branch -M main
The stuff from line 57 to the bottom is not needed as well. Again, this is to set up a new branch, but since here we hare cloning a repo, the branch is already there.

2023-03-03 05:00 UTC, mjwen commented on docs/devtool/github.md
> +Generate SSH key and add it to your GitHub account, follow the tutorial here [Google link](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-
This is NOT a `Google` link

2023-03-03 05:00 UTC, mjwen commented on docs/devtool/github.md
> +Click on `Code` to copy the URL
In your figure, you may want to show copy the SSH address, and explicitly say it in the text.

2023-03-03 05:00 UTC, mjwen commented on docs/devtool/github.md
> +$ ssh-keygen -t rsa -b 4096 -C "olanrewajuemmanuel145584@gmail.com"
How about changing the email address to a general one, like `your_email@gmail.com`, but not using yours. And explain below briefly saying that `You can change the email address to yours or any other comments.`

2023-03-03 05:00 UTC, mjwen commented on docs/devtool/github.md
> +* Clone the repository using the SSH URL. For example, if the repository URL is 'git@github.com:USERNAME/REPOSITORY.git'. You can clone it by running this command:
You can highlight the address using \` (the key below `esc` on your keyboard), not ' (the key before `return`). This is markdown syntax.

2023-03-03 05:00 UTC, mjwen commented on docs/devtool/github.md
> +```{figure} ../image/SSH.png
You need to briefly explain that `USERNAME` and `REPOSITORY` need to be replaced.

2023-03-03 05:00 UTC, mjwen commented on docs/devtool/github.md
> +* Select the branch with your changes from the **base** dropdown menu and the branch you want to merge into from the **compare** dropdown menu.
These are great!

2023-03-03 05:44 UTC, Olanrewajuemmanuelabiodun commented on docs/devtool/github.md
> +* Select the branch with your changes from the **base** dropdown menu and the branch you want to merge into from the **compare** dropdown menu.
Okay. Necessary corrections done.

2023-03-03 15:15 UTC, merged